[2024-07-14T18:52:24.204+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-14T18:52:24.238+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: db_and_http.branch_task manual__2024-07-14T18:52:08.275879+00:00 [queued]>
[2024-07-14T18:52:24.254+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: db_and_http.branch_task manual__2024-07-14T18:52:08.275879+00:00 [queued]>
[2024-07-14T18:52:24.255+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-07-14T18:52:24.280+0000] {taskinstance.py:2330} INFO - Executing <Task(BranchPythonOperator): branch_task> on 2024-07-14 18:52:08.275879+00:00
[2024-07-14T18:52:24.289+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=1004) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-07-14T18:52:24.291+0000] {standard_task_runner.py:63} INFO - Started process 1005 to run task
[2024-07-14T18:52:24.293+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'db_and_http', 'branch_task', 'manual__2024-07-14T18:52:08.275879+00:00', '--job-id', '20', '--raw', '--subdir', 'DAGS_FOLDER/db_and_http_dag.py', '--cfg-path', '/tmp/tmpg19jukfk']
[2024-07-14T18:52:24.296+0000] {standard_task_runner.py:91} INFO - Job 20: Subtask branch_task
[2024-07-14T18:52:24.372+0000] {task_command.py:426} INFO - Running <TaskInstance: db_and_http.branch_task manual__2024-07-14T18:52:08.275879+00:00 [running]> on host 26fab3728191
[2024-07-14T18:52:24.553+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='db_and_http' AIRFLOW_CTX_TASK_ID='branch_task' AIRFLOW_CTX_EXECUTION_DATE='2024-07-14T18:52:08.275879+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-07-14T18:52:08.275879+00:00'
[2024-07-14T18:52:24.555+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-14T18:52:24.619+0000] {baseoperator.py:400} WARNING - BranchPythonOperator.execute cannot be called outside TaskInstance!
[2024-07-14T18:52:24.639+0000] {python.py:237} INFO - Done. Returned value was: more_than_hundred
[2024-07-14T18:52:24.641+0000] {branch.py:36} INFO - Branch into more_than_hundred
[2024-07-14T18:52:24.642+0000] {skipmixin.py:178} INFO - Following branch more_than_hundred
[2024-07-14T18:52:24.677+0000] {skipmixin.py:246} INFO - Skipping tasks [('less_than_hundred', -1)]
[2024-07-14T18:52:24.735+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-14T18:52:24.777+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=db_and_http, task_id=branch_task, run_id=manual__2024-07-14T18:52:08.275879+00:00, execution_date=20240714T185208, start_date=20240714T185224, end_date=20240714T185224
[2024-07-14T18:52:24.861+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-07-14T18:52:25.032+0000] {taskinstance.py:3503} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-07-14T18:52:25.036+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
